### PR TITLE
Upload package to PyPI

### PR DESCRIPTION
**Pull request by hanefi**
Thanks for your awesome work in this Osman abi :)

We decided to use your package in a project and having to install it manually was cumbersome. I took the liberty to publish this package in https://pypi.python.org/pypi/TurkishStemmer. 

As I do not claim the ownership of this work, I can make the necessary changes to the package details and transfer the ownership to you.

I am glad that now we can run `pip install TurkishStemmer` now

### CODE REVIEW

**Comment by tbrknt** [comment]
I have installed TurkishStemmer with pip. Then, when I have tried to import it, it resulted in the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../site-packages/TurkishStemmer/__init__.py", line 3, in <module>
    from .states import NounState, DerivationalState, NominalVerbState
ImportError: No module named states

It results in this error on both of Python 2.7 and Python 3.5.

When I checked [pypi package](https://pypi.org/project/TurkishStemmer/#files), it seems that most of the code is missing on the package.

Note: Since issues were disabled on both repositories, I thought that this is the right place to mention it.

**Comment by hanefi** [comment]
@tbrknt I added the missing modules, and incremented the version number.

I tested on both Python 3.7 and 2.7.15 and both seems to work.

Please run `pip install --upgrade TurkishStemmer` and let's hope that it'll work this time

Also, I enabled issues for further use. Thanks for the heads-up

**Comment by otuncelli** [comment]
@hanefi It seems setup doesn't install files inside the 'resources' folder but everything else seems ok to me. If you can include them as well i'll merge the PR. Thanks for your contribution and the package 👍

I've changed the setup code a little bit and also included an empty `__init__.py` in the resources folder. I tested on Python 3.65.
```python
#!/usr/bin/env python
import setuptools

with open("README.md", "r", encoding='utf-8') as fh:
    long_description = fh.read()

setuptools.setup(
    name='TurkishStemmer',
    version='1.2',
    description='Turkish Stemmer',
    long_description=long_description,
    long_description_content_type="text/markdown",
    author='Hanefi Onaldi',
    author_email='abdullahanefi16@gmail.com',
    url='https://github.com/hanefi/turkish-stemmer-python',
    packages=setuptools.find_packages(),
    package_data={'':['*.txt'],},
   )
```

**Comment by hanefi** [comment]
I extracted the package at [PyPI](https://pypi.org/project/TurkishStemmer/1.3/#files) and the txt resources are there.

I guess having an empty `__init__.py` file is a better alternative than recursively checking for txt files (What I mean is having a `**/*.txt` rather than `*.txt` there)

**Pull request merged**
